server:
  port: 5000

spring:
  application:
    name: LexChain


  config:
    import: "optional:file:.env[.properties]"


  data:
    mongodb:
      uri: ${MONGO_URI}



  threads:
    virtual:
      enabled: true

blockchain:
  polygon:
    amoy:
      rpc-url: https://rpc-amoy.polygon.technology/